# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chooseInterfere' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'Firebase/Analytics'
	pod 'Firebase/Database'
	pod 'CodableFirebase'
  # Pods for chooseInterfere

  target 'chooseInterfereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chooseInterfereUITests' do
    # Pods for testing
  end

end
